language: python
dist: xenial
python: "3.7"
script:
  - pip install awscli
  - mkdir ~/.aws
  - echo "[profile iterative]" >> ~/.aws/config
  - echo "region = us-east-2" >> ~/.aws/config
  - echo "[iterative]" >> ~/.aws/credentials
  - echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
  - echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
  - ./deploy.sh
