language: python
dist: xenial
python: '3.7'
env:
  global:
  # AWS_ACCESS_KEY_ID
  - secure: QYCeJ5lyrMoG28bMRZIANLrUozO9/PaksVWuUh3ZkBebI3lzG6j3ISiTS83SMisaQCDe6/CjlwdckdkQf5SNBhkUtHvFbX9r1vGBOrdko2dj4I8XxP8+oR5Es4nFn55cyiTu58rcZtg9uO8zj4xOFLxJdpWMteuA2QwaW+CXUbD+7fH3K78eYMeXyT6Y9SV9qh2LRHS/+U7oXioMHOyqKfJVno4S0zqLjeUy7MDuLORmfxzn+tALsxJMGKK3FIeqbRvmfiyj4Qg3xPYq3i9rSwH8VpKjhLW3c//L1fKIBnamaYAITwZ8ynFtWy4RXNBw71+wAmy6cM1AKWtRpXttOOwpdO5qDDuijNbTx/bRsZkqeKT2SZVYLNw7PtgnQ/zv3Cf21npq82Pq0lLIJ2KcPyPt9xdQ93KoAJXN+yNn8RuNyPPtxd/aCToZ2PXTrjcF5LyL50OztxvYLG0PqMP97RSqfQHGae25fhwH+STmoKWR7uNfFJsLCLqkvpVeTc5KZdEmKTAMqZZih5ROhMFLzwSFkLdI9Y5Rd0HLrq8FjapZCi3hYrQ81ZvhIPObPSDXT6S+gurJms/e4LpTDA+EcH6t4Nx4KZFqE1+P2IcKbd4lYhsaC9MgVWFOkB89FpI7z5EN6hymms5duuatxU040vlK/If4Z11WELJ8r9flHHE=
  # AWS_SECRET_ACCESS_KEY
  - secure: nBOr0SFLMDWHZkJsbAw6fWaCI4FwfQtCbQIEa5bJclFoowRvwQVnc5MAeNvustYuEq2qie9Tq0UXmFtNVsBrtA1Fm2qxLuBWU9oDON3kaHTXV9JvnhrJNSPRB9mNemYa1Vipg02W32CLvTD5nfss8BP+VvlC33QxrjBCAPyZ+bpbGBvChddrLdM7MWzNiXy4dxCPZRCTwk2xnCmejGrk7BTZ285RwO8Bvmlsd+Hd+pmt/gjn0OCFumt2vYnGkh4Ki7rvCMXFOQv1eMrFlBBHnYUw2f6Z+FE50L/pPx92ixmztivm5SjT4EltVklffr4WEkVs84ATopYjwQLNXpH5ke4rDhtoq0JsF9eufMjHIHqA/wKaxhOvzy1oKYbFXQ/fBPnE5+Tc3JHmnl3W7Ih/8bN5LPuOUxnMtay/G/QFNSEOXHRsnb/PWoPw2O07jLl55DmZ1Ilz4QlxFzhgPd+2vxRqJjVuw+57ZtyhJ8nvFv9fMYQNx3zMf1dnOvInlmNGnj11mQz3eVnc1luMdDGHUvziumha1UxbSKljvUl/SN+9p2ZSp0va29Qi3rkHSH6IPjMGds+ngFyo9QS9DlJ8e+jQ+YwULuGtrm5y9d5WqD/cYrH4AIKmzGJE9x216UA6F/bQwTOGSHu/dxp4y9dqQFlfL8LPSSn3+bsx8EfLvAs=
script:
- pip install awscli
- mkdir ~/.aws
- echo "[profile iterative]" >> ~/.aws/config
- echo "region = us-east-2" >> ~/.aws/config
- echo "[iterative]" >> ~/.aws/credentials
- echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
- echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
- "./deploy.sh"
